# Generated by Django 5.0.3 on 2024-03-13 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowing', '0001_initial'),
        ('libraryCatalog', '0001_initial'),
        ('userManager', '0002_rename_user_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryCatalog.book'),
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManager.student'),
        ),
    ]
