# Generated by Django 5.0.2 on 2024-03-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Borrowing', '0003_alter_borrowedbook_borrowed_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowedbook',
            old_name='returned_date',
            new_name='return_date',
        ),
    ]
