# Generated by Django 3.0.5 on 2024-03-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarySystem', '0004_auto_20240312_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuedbook',
            old_name='isbn',
            new_name='book_isbn',
        ),
    ]
