# Generated by Django 3.0.5 on 2024-03-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Borrowing', '0004_rename_returned_date_borrowedbook_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
