# Generated by Django 5.0.3 on 2024-03-17 15:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Borrowing', '0005_alter_borrowedbook_return_date'),
        ('LibraryCatalog', '0005_alter_review_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrowedbook',
            unique_together={('student', 'book')},
        ),
    ]
