# Generated by Django 3.0.5 on 2024-03-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarySystem', '0002_auto_20240312_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedbook',
            name='isbn',
        ),
        migrations.AddField(
            model_name='issuedbook',
            name='book_isbn',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
