# Generated by Django 3.0.5 on 2024-03-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarySystem', '0003_auto_20240312_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuedbook',
            old_name='book_isbn',
            new_name='isbn',
        ),
    ]
