# Generated by Django 5.0.3 on 2024-03-13 14:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userManager', '0002_rename_user_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('number_of_copies', models.IntegerField()),
                ('currently_available_copies', models.IntegerField()),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('genre', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraryCatalog.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('date', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryCatalog.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManager.student')),
            ],
        ),
    ]
