# Generated by Django 5.0.3 on 2024-03-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryCatalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
