# Generated by Django 5.0.3 on 2024-03-15 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryCatalog', '0002_alter_genre_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'author')},
        ),
    ]
