# Generated by Django 5.0.3 on 2024-03-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryCatalog', '0003_alter_book_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
