# Generated by Django 5.0.3 on 2024-03-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryCatalog', '0004_alter_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='student',
            field=models.CharField(max_length=100),
        ),
    ]
